"""Constantes do protocolo de aplicacao SMARTROOM/1.0."""

PROTOCOL_ID = "SMARTROOM/1.0"

MANAGER_ID = "MANAGER"
CLIENT_TEACHER_ID = "CLIENT_TEACHER"

SOURCE_TYPE_SENSOR = "SENSOR"
SOURCE_TYPE_ACTUATOR = "ACTUATOR"
SOURCE_TYPE_MANAGER = "MANAGER"
SOURCE_TYPE_CLIENT = "CLIENT"

SOURCE_TYPES = {
    SOURCE_TYPE_SENSOR,
    SOURCE_TYPE_ACTUATOR,
    SOURCE_TYPE_MANAGER,
    SOURCE_TYPE_CLIENT,
}

MESSAGE_HELLO = "HELLO"
MESSAGE_ACK = "ACK"
MESSAGE_ERROR = "ERROR"
MESSAGE_PRESENCE_UPDATE = "PRESENCE_UPDATE"
MESSAGE_STUDENT_CHECKIN = "STUDENT_CHECKIN"
MESSAGE_PROJECTOR_SWITCH = "PROJECTOR_SWITCH"
MESSAGE_ACTUATOR_COMMAND = "ACTUATOR_COMMAND"
MESSAGE_ATTENDANCE_REQUEST = "ATTENDANCE_REQUEST"
MESSAGE_ATTENDANCE_RESPONSE = "ATTENDANCE_RESPONSE"

MESSAGE_TYPES = {
    MESSAGE_HELLO,
    MESSAGE_ACK,
    MESSAGE_ERROR,
    MESSAGE_PRESENCE_UPDATE,
    MESSAGE_STUDENT_CHECKIN,
    MESSAGE_PROJECTOR_SWITCH,
    MESSAGE_ACTUATOR_COMMAND,
    MESSAGE_ATTENDANCE_REQUEST,
    MESSAGE_ATTENDANCE_RESPONSE,
}

ROLE_PRESENCE_SENSOR = "PRESENCE_SENSOR"
ROLE_CARD_READER = "CARD_READER"
ROLE_PROJECTOR_SWITCH = "PROJECTOR_SWITCH"
ROLE_LIGHT_ACTUATOR = "LIGHT_ACTUATOR"
ROLE_PROJECTOR_ACTUATOR = "PROJECTOR_ACTUATOR"
ROLE_AC_ACTUATOR = "AC_ACTUATOR"
ROLE_TEACHER_CLIENT = "TEACHER_CLIENT"

SENSOR_PRESENCE_ID = "SENSOR_PRESENCE_01"

ACT_LIGHT_ID = "ACT_LIGHT_01"
ACT_PROJECTOR_ID = "ACT_PROJECTOR_01"
ACT_AC_ID = "ACT_AC_01"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 5050
DEFAULT_ABSENCE_TIMEOUT_SECONDS = 15 * 60
DEMO_ABSENCE_TIMEOUT_SECONDS = 15
SHUTDOWN_HOUR = 23
SOCKET_BUFFER_SIZE = 4096
MAX_MESSAGE_BYTES = 64 * 1024
