@startuml

title Aceitar conexão

control componente
participant gerenciador
database db

componente -> gerenciador : connect()
activate gerenciador
note over componente
  HEADER
  - id_componente: int
  - tipo_componente : int
end note

alt Id não reconhecido
  gerenciador -> gerenciador : Falha de id_componente

else Tipo não reconhecido
  gerenciador -> gerenciador : Falha de tipo_componente
  deactivate gerenciador

else Aceito
end

gerenciador -> db : GET componente/{id}/id
activate gerenciador
activate db
note right of db
  Obter componente por ID
end note

alt Id não cadastrado
  gerenciador <- db : [null]

  gerenciador -> gerenciador : Componente não cadastrada

else Tipo imcompatível
  gerenciador <- db : [component]

  gerenciador -> gerenciador : Incompatibilidade entre tipo e id
  deactivate gerenciador

else Aceito
end

gerenciador <- db : [componente]
deactivate db
activate gerenciador

gerenciador -> gerenciador : [Ok!]
deactivate gerenciador


@enduml