@startuml

title Ligar iluminacao e ar-condicionado

control "Sensor de presenca" as presence_sensor
participant "Gerenciador" as manager
control "ACT_LIGHT_01" as light
control "ACT_AC_01" as ac

presence_sensor -> manager : PRESENCE_UPDATE
activate manager
note over presence_sensor
  payload:
  {
    "presence_detected": true
  }
end note

manager -> light : ACTUATOR_COMMAND
activate light
note right of light
  payload:
  {
    "actuator_id": "ACT_LIGHT_01",
    "command": "ON",
    "reason": "presence_detected"
  }
end note
light --> manager : ACK
deactivate light

manager -> ac : ACTUATOR_COMMAND
activate ac
note right of ac
  payload:
  {
    "actuator_id": "ACT_AC_01",
    "command": "ON",
    "reason": "presence_detected"
  }
end note
ac --> manager : ACK
deactivate ac

deactivate manager

@enduml
