@startuml

title Apagar luzes e ligar projetor

control "Chave do projetor" as projector_switch
participant "Gerenciador" as manager
control "ACT_LIGHT_01" as light
control "ACT_PROJECTOR_01" as projector

projector_switch -> manager : PROJECTOR_SWITCH
activate manager
note over projector_switch
  payload:
  {
    "projector_switch_on": true
  }
end note

manager -> light : ACTUATOR_COMMAND
activate light
note right of light
  payload:
  {
    "actuator_id": "ACT_LIGHT_01",
    "command": "OFF",
    "reason": "projector_switch_on"
  }
end note
light --> manager : ACK
deactivate light

manager -> projector : ACTUATOR_COMMAND
activate projector
note right of projector
  payload:
  {
    "actuator_id": "ACT_PROJECTOR_01",
    "command": "ON",
    "reason": "projector_switch_on"
  }
end note
projector --> manager : ACK
deactivate projector

deactivate manager

@enduml
