@startuml

title Acender as luzes e desligar projetor

control sensor
participant gerenciador
control atuador

sensor -> gerenciador : movie_mode_off()
activate gerenciador
note over sensor
  DATA:
  - modo_projetor = 0
end note

gerenciador -> atuador : lights_on()
activate atuador
note right of atuador
  DATA:
  - modo_iluminacao = 1
end note

gerenciador <- atuador : [Ok!]
deactivate atuador

gerenciador -> atuador : projetor_off()
activate atuador
note right of atuador
  DATA:
  - modo_projetor = 0
end note

gerenciador <- atuador
deactivate atuador
deactivate gerenciador


@enduml