@startuml

title Acender as luzes e desligar projetor

participant gerenciador
control atuador

alt now() < 23h
  gerenciador -> gerenciador : null
  activate gerenciador
  deactivate gerenciador

else now() >= 23h
end

gerenciador -> gerenciador: midnight_gospel()
activate gerenciador

gerenciador -> atuador : lights_off()
activate atuador
note right of atuador
  DATA:
  - modo_iluminacao = 0
end note

gerenciador <- atuador : [Ok!]
deactivate atuador

gerenciador -> atuador : projetor_off()
activate atuador
note right of atuador
  DATA:
  - modo_projetor = 0
end note

gerenciador <- atuador : [Ok!]
deactivate atuador

gerenciador -> atuador : air_cond_off()
activate atuador
note right of atuador
  DATA:
  - modo_ar_condicionado = 0
end note

gerenciador <- atuador : [Ok!]
deactivate atuador
deactivate gerenciador


@enduml