@startuml

title Obter lista de presenca

actor "Cliente/professor" as teacher_client
participant "Gerenciador" as manager
database "lista_presenca" as attendance_list

teacher_client -> manager : ATTENDANCE_REQUEST
activate manager
note over teacher_client
  payload: {}
end note

manager -> attendance_list : obter lista de presenca
activate attendance_list
attendance_list --> manager : students
deactivate attendance_list

manager --> teacher_client : ATTENDANCE_RESPONSE
note right of manager
  payload:
  {
    "students": [
      {
        "student_number": "001",
        "student_name": "Aluno 1"
      }
    ]
  }
end note

deactivate manager

@enduml
