@startuml

title Obtenção de informações

actor user
participant sistema
database db

user -> sistema : QR image

sistema -> sistema : decode

sistema -> db : patch

sistema <- db : [id]

sistema -> sistema : send message

user <- sistema : [id]

@enduml