@startuml

title Cadastro de nova enquete\nCompleto

actor user
participant qrscan
participant poll_manager
database db

user -> qrscan : ws/qrscan
activate qrscan
note right of user
  file: b'image'
end note

alt Sem imagem
  user <- qrscan : Falha: Imagem não informada!

else QR não reconhecido

  user <- qrscan : Falha: QR não reconhecido
  deactivate qrscan

else QR reconhecido
end

qrscan -> qrscan : content = decode(file)
activate qrscan

alt Conteúdo mal formatado
  user <- qrscan : Falha: conteúdo mal formatado
  deactivate qrscan

else Conteúdo aceito
end

qrscan -> poll_manager : POST poll/{label}/label
activate qrscan
activate poll_manager
note right of qrscan
  opcode: [:|]
  label: [|:|]
  questions: [|:]
end note

alt opcode not in [w, r]
  qrscan <- poll_manager : Falha: Opcode inválido
  deactivate poll_manager
  
  user <- qrscan : Falha: Opcode inválido
  deactivate qrscan

else new_poll = r: VER OBTER ENQUETE
else new_poll = w
end

alt Campo "label" mal formatado
  qrscan <- poll_manager : Falha: Campo "label" inválido 
  activate poll_manager
  activate qrscan

  user <- qrscan : Falha: Campo "label" inválido 

else Campo "questions" mal formatado
  qrscan <- poll_manager : Falha: Campo "questions" inválido 
  deactivate poll_manager

  user <- qrscan : Falha: Campo "questions" inválido 
  deactivate qrscan

else Campos válidos
end

poll_manager -> db : POST /{label}/new-poll
activate db
note right of db
  INSERT INTO poll (title, questions)
  VALUES ($label, $questions)
end note

activate poll_manager
activate qrscan

poll_manager <- db : [Ok!]
deactivate db

qrscan <- poll_manager : [Ok!]
deactivate poll_manager

user <- qrscan : [Ok!]
deactivate qrscan

@enduml