@startuml

title Obtenção de informações

actor user
participant sistema
database db

user -> sistema : QR image

sistema -> sistema : decode

sistema -> db : save

sistema <- db : [Ok!]

user <- sistema : [Ok!]

@enduml